//// <auto-generated />
//#nullable enable
//namespace ServiceRegistrationGenerator.Example
//{
//    static partial class ServiceCollectionExtensions
//    {
//        public static partial Microsoft.Extensions.DependencyInjection.IServiceCollection AddServices(this Microsoft.Extensions.DependencyInjection.IServiceCollection services)
//        {
//            // .*Service.*
//            return services;
//        }
//    }
//}
